rails/esestra/config/routes.rb
Esestra::Application.routes.draw do
  resources :specialties
  resources :surgeries, only: [:index]
  match 'calendar' => 'surgeries#calendar'

end

rails/esestra/app/models/address.rb
class Address < ActiveRecord::Base
  has_one :surgery, dependent: :restrict

  validates_presence_of :city, :street, :surgery
  validates_length_of :city, maximum: 200
  validates_length_of :street, maximum: 200
end

rails/esestra/app/models/adress.rb
class Adress < ActiveRecord::Base
  validates_presence_of :city, :street
  validates_length_of :city, maximum: 200
  validates_length_of :street, maximum: 200
end

rails/esestra/app/models/day_of_week.rb
class DayOfWeek < ActiveEnum::Base
  value id: 1, name: 'monday', abbreviation: 'mo'
  value id: 2, name: 'tuesday', abbreviation: 'tu'
  value id: 3, name: 'wednesday', abbreviation: 'we'
  value id: 4, name: 'thursday', abbreviation: 'th'
  value id: 5, name: 'friday', abbreviation: 'fr'
  value id: 6, name: 'saturday', abbreviation: 'sa'
  value id: 7, name: 'sunday', abbreviation: 'su'
end

rails/esestra/app/models/opening_time.rb
#encoding: utf-8


class OpeningTime < ActiveRecord::Base
  enumerate :day_of_week
  belongs_to :surgery

  validates_presence_of :day_of_week
  validates_presence_of :surgery
  validates_presence_of :begin
  validates_presence_of :end
  validates_length_of :note, maximum: 40
  validate :begin_must_be_less_than_end
  validate :begin_must_be_rounded_to_quarters

  def begin_must_be_less_than_end
    if not self.begin.nil? and not self.end.nil?
      errors[:base] << I18n.t('activerecord.errors.models.opening_time.base.begin_must_be_less_than_end') unless self.begin < self.end
    end
  end

  def begin_must_be_rounded_to_quarters
    if not self.begin.nil?
      errors[:base] << I18n.t('activerecord.errors.models.opening_time.base.begin_must_be_rounded_to_quarters') unless self.begin == round_time_to_quarter(self.begin)
    end
  end

  # viz http://stackoverflow.com/questions/449271/how-to-round-a-time-down-to-the-nearest-15-minutes-in-ruby
  def round_time_to_quarter(t)
    Time.at(t.to_i - t.sec - t.min % 15 * 60)
  end

end

rails/esestra/app/models/specialty.rb
class Specialty < ActiveRecord::Base
  has_many :surgeries, dependent: :restrict

  validates_uniqueness_of :name
  validates_presence_of :name
  validates_length_of :name, maximum: 40
end

rails/esestra/app/models/surgery.rb
class Surgery < ActiveRecord::Base
  belongs_to :specialty
  belongs_to :address, dependent: :delete
  has_many :opening_times, dependent: :delete_all

  validates_uniqueness_of :name
  validates_presence_of :name, :specialty, :address
  validates_length_of :name, maximum: 40
  validates_length_of :phone, maximum: 200
  validates_length_of :email, maximum: 200
  validates_length_of :web, maximum: 200

end

rails/esestra/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

rails/esestra/app/controllers/specialties_controller.rb
class SpecialtiesController < ApplicationController
  def index
    @specialties = Specialty.order(:name).all
  end

  def show
    redirect_to edit_specialty_path, id: params[:id]
  end

  def new
    @specialty = Specialty.new
    render :form
  end

  def edit
    @specialty = Specialty.find(params[:id])
    render :form
  end

  def create
    @specialty = Specialty.create(params[:specialty])
    render :form
  end

  def update
    @specialty = Specialty.find(params[:id])
    @specialty.update_attributes(params[:specialty])
    render :form
  end

  def destroy
    @specialty = Specialty.find(params[:id])
    @specialty.destroy
    redirect_to specialties_path
  end

end

rails/esestra/app/controllers/surgeries_controller.rb
class SurgeriesController < ApplicationController
  def index
    @surgeries = Surgery.joins(:specialty).order('specialties.name, name').all
  end

  def calendar

  end
end

rails/esestra/app/helpers/application_helper.rb
module ApplicationHelper
end

rails/esestra/app/helpers/specialties_helper.rb
module SpecialtiesHelper
end

rails/esestra/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= t('.title') %></title>
  <%= stylesheet_link_tag  "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.5/jquery.min.js"></script>
  <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js"></script>
  <script src="http://jquery-ui.googlecode.com/svn/trunk/ui/i18n/jquery.ui.datepicker-cs.js"></script>

  <link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/base/jquery-ui.css" rel="stylesheet"
        type="text/css"/>

</head>

<body>

<div id="header">
  <div class="center">
    <span id="title"><%= t('.title') %></span>
    <span id="subtitle"><%= t('.subtitle') %></span>
  </div>
</div>

<div class="center" id="main">
<%= yield %>
</div>

</body>
</html>

rails/esestra/app/views/specialties/_form.html.erb
#encoding: utf-8

<h1>Specializace</h1>
<br>

<%= form_for(@specialty) do |f| %>
    <% if @specialty.errors.any? %>
        <div id="error_explanation">
          <ul>
            <% @specialty.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
        <br>
    <% end %>

    <div class="field">
      <%= f.label :name, 'Jméno' %>
      <%= f.text_field :name %>
    </div>
    <br>
    <div class="actions">
      <%= f.submit 'Uložení' %>
    </div>
<% end %>

rails/esestra/app/views/specialties/form.html.erb
#encoding: utf-8

<script>
    $(document).ready(function() {
        set_submit_button($('form :submit'), $('form .field'));
    });
</script>

<h1><%= t('activerecord.models.specialty') %></h1>
<br>

<%= form_for(@specialty) do |f| %>
    <div class="actions">
      <%= f.submit t('form.save'), class: 'button' %>
      <% if @specialty.id? %>
          <%= link_to t('form.insert'), new_specialty_path, class: 'button' %>
          <%= link_to t('form.delete'), @specialty, data: {confirm: t('form.delete')}, method: :delete, class: 'button' %>
          <%= link_to t('form.load'), edit_specialty_path(@specialty), class: 'button' %>
      <% end %>
      <%= link_to t('form.index'), specialties_path, class: 'button' %>
    </div>

    <% if @specialty.errors.any? %>
        <div id="error_explanation">
          <ul>
            <% @specialty.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
        <br>
    <% end %>

    <div class="field">
      <%= f.label :name, t('activerecord.attributes.specialty.name') %>
      <%= f.text_field :name %>
    </div>
    <br>
<% end %>

rails/esestra/app/views/specialties/index.html.erb
#encoding: utf-8

<h1><%= t('.title') %></h1>
<br>

<%= link_to t('form.insert'), new_specialty_path, class: 'button' %>
<br><br>

<table class="index">
  <tr class="gradient">
    <th class="index"><%= t('activerecord.attributes.specialty.name') %></th>
    <th class="index link"></th>
    <th class="index link"></th>
  </tr>

<% @specialties.each do |specialty| %>
  <tr class="<%= cycle('white', 'shadow') %>">
    <td class="index"><%= specialty.name %></td>
    <td class="index link"><%= link_to t('form.update'), edit_specialty_path(specialty) %></td>
    <td class="index link"><%= link_to t('form.delete'), specialty, data: { confirm: t('form.sure') }, method: :delete %></td>
  </tr>
<% end %>
</table>

rails/esestra/app/views/surgeries/index.html.erb
#encoding: utf-8

<div id="surgeries">
  <% @surgeries.each do |surgery| %>
      <div class="surgery">
        <div class="specialty"><%= surgery.specialty.name %></div>
        <div class="address">
          <p><%= surgery.address.city %></p>

          <p><%= surgery.address.street %></p>
        </div>
        <div class="tlacitko">
          <form method="link" action="calendar.html">
            <input class="button" type="submit" value="Objednat">
          </form>
        </div>
        <div class="name"><%= surgery.name %></div>
        <div class="contacts">
          <p>Tel: <%= surgery.phone %></p>

          <p>Email: <%= surgery.email %></p>

          <p>Web: <a href="http://<%= surgery.web %>"><%= surgery.web %></a></p>
        </div>
        <div class="opening_times">
          <table>
            <% DayOfWeek.to_select.each do |day| %>
                <tr class="opening_times">
                  <td class="width0">
                    <div class="day width0">
                      <div class="bottom width0"><%= day[0] %></div>
                    </div>
                  </td>
                  <% surgery.opening_times.order(:begin).where(day_of_week: (day[1])).each do |opening_time| %>
                      <td class="width1">
                        <div class="time width1">
                          <div class="top width2"><%= opening_time.note %></div>
                          <div class="bottom width1">
                            <div class="one width3"><%= opening_time.begin.strftime('%H:%M')%></div>
                            <div class="two width4">-</div>
                            <div class="three width3"><%= opening_time.end.strftime('%H:%M')%></div>
                          </div>
                        </div>
                      </td>
                  <% end %>
                </tr>
            <% end %>
          </table>
        </div>
      </div>
  <% end %>
</div>